config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  get 'todos', to: 'todos#index'
  get 'todos/new', to: 'todos#new'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'todos_edit'
  get 'todos_completed/:id', to: 'todos#completed', as: 'todo_completed'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get '/todos_lista', to: 'todos#lista'

  #-------de esa manera de hacen las rutas-------
  #--------para refactorizar---------
  # resources :todos
  #get 'todos/index', to: 'todos#index' ---->el primero es lo que se escribe en la url y el segundo es 'controlador#metodo'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    ##validaciones   
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :find_todo, only: [ :show, :edit, :completed, :update, :destroy ]
    
    #antes de que suceda cualquier metodo llama a la funcion find_todo, que se define en private, este metodo se utilizara solo (only) en los metodos del array especificado.

    def  index
        @todos = Todo.all
        # index es un metodo que contiene un avariable de instancia @todos. esta variable almacena todos los "todos" existentes.
    end 
    def new
        @todo = Todo.new
    end
    def create
        @todo = Todo.new(todo_params)
        if @todo.save
            redirect_to todos_path 
            #esto redirige al index paa que al crear un nnueva actividad ésta al ser creada te devulevala comienzo con la lista completa
        else
            redirect_to todos_path, notice:'Ingrese la tarea'
        end 
    end

    def show   
    end

    def edit    
    end 

    def completed
        @todo.completed = true
        @todo.save
        redirect_to todos_path
    end 

    def update
        @todo.update(todo_params)
        redirect_to todos_path
    end  

    def destroy
        @todo.destroy
        redirect_to todos_path
    end

    def lista
        @todos = Todo.all
        @todos_completed = Todo.where(completed: true)
        @todos_uncompleted = Todo.where(completed: [false, nil])
    end  

    private
    def todo_params
        params.require(:todo).permit(:description)
    end
    def find_todo
        @todo = Todo.find(params[:id])
    end    
    
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
  <%= render 'todos/navbar' %>

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with model: @todo, local: true do |f| %>
    <%= f.text_field :description %>
        <%= f.submit "Crear" %>
     
 
    <% end %>
  </div>
</div>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top  navbar-dark bg-dark">
  <a class="navbar-brand" href="#">To Do</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav  nav mr-auto">
      <li class="nav-item px-5">
        <%= link_to 'Inicio', root_path %>
      </li>
      <li class="nav-item px-5">
        <%= link_to 'Crear', todos_new_path %>
      </li>
      <li class="nav-item px-5">
        <%= link_to 'Lista', todos_lista_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/todos/edit.html.erb
<div class="my-5 py-3">
    <%= render 'todos/form' %>
</div>

app/views/todos/index.html.erb
<div class="my-5 py-3">
    <div class="row">
        <% @todos.each do |todo| %>
            <div class="card my-1 col-md-6 col-sm-12">
                <div class="card-body mx-3 ">
                    <h4>
                        <%= link_to todo.description, todo %>
                    </h4 class="text-dark text-decoration-none">
                    <% if  todo.completed == true %>
                        <div class="badge badge-success text-wrap" style="width: 6rem;">
                            Tarea completada
                        </div>
                    
                    <% else %>
                    <button type="button" class="btn btn-outline-success"> 
                        <%= link_to "Completar", todo_completed_path(todo)%>
                    </button>
                    <button type="button" class="btn btn-outline-danger">
                        <%= link_to "Borrar", todo, method: :delete %>
                    </button>
                    <button type="button" class="btn btn-outline-info">
                        <%= link_to "Editar", todos_edit_path(todo) %>
                    </button> 
                    <% end %>
                    
                </div>
            </div>
        <% end %>
    </div>
    <button type="button" class="btn btn-outline-info p-3">
        <%= link_to "Crear nueva tarea", todos_new_path %>
    </button>    
    
</div>

app/views/todos/lista.html.erb
<div class="row my-5 py-3">

    <div class="card my-1 col-md-6 col-sm-12">
    <h1 class="text-success">Completados</h1>
    <% @todos_completed.each do |t| %>
        <blockquote class="blockquote">
            <p class="mb-0">&nbsp;&nbsp;<%= t.description %></p>
        </blockquote>  
    <% end %>
    </div>

    <div class="card my-1 col-md-6 col-sm-12">
        <h1 class="text-danger">No Completados</h1>
    <% @todos_uncompleted.each do |t| %>
        <blockquote class="blockquote">
            <p class="mb-0">&nbsp;&nbsp;<%= t.description %></p>
        </blockquote>
    <% end %>
    </div>
</div>

app/views/todos/new.html.erb
<div class="row my-5 py-3">
    
    <%= render 'todos/form' %>
   
</div>

app/views/todos/show.html.erb
<div class="my-5 py-3">
    <div class="card">
        <div class="card-body">
            <%= @todo.description %>
        </div>
    </div>
</div>